version: '3'
services:
  # db:
  #   image: mysql
  #   volumes:
  #      - datafiles:/var/lib/mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: Passw0rd

  mvc:
    build:
      context: .
      dockerfile: Dockerfile
    #depends_on:
    #   - db
    ports:
      - "8888:80"
    restart: always
    environment:
      # - DBHOST=db
      - ASPNETCORE_ENVIRONMENT=Development

  web:
    # build: .
    build:
      context: deliverydashboard
      dockerfile: Dockerfile
    # Change the port if you'd like to expose your project locally on a
    # different port, for example if you already use port 8000 for
    # something else.
    ports:
      - "80:80"
    #volumes:
      #- ".:/app:rw"
    # There is currently a bug: https://github.com/facebook/create-react-app/issues/8688#issuecomment-602149917
    tty: true
    # The default command that the container starts with. If you'd like to run
    # the project locally in Live configuration, you will need to change this.
    # See https://docs.divio.com/en/latest/how-to/local-in-live-mode
    command: npm run start
    # update:1.0
volumes:
  datafiles: