# apiVersion: v1
# kind: Service
# metadata:
#   name: supermarketapi
# spec:
#   selector:
#     app: supermarketapi
#   ports:
#   - port: 81       # User uses this one to communicate with the cluster.
#     targetPort: 80 # forwards them to port 80 of the target Pods(containers)
#   type: LoadBalancer