apiVersion: v1
kind: Service
metadata:
  name: supermarketapi-service
  labels:
    app: supermarketapi
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: supermarketapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermarketapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supermarketapi
  template:
    metadata:
      labels:
        app: supermarketapi
    spec:
      containers:
      - name: supermarketapi
        image: ricardo21/supermarketapi:v5
        ports:
        - containerPort: 80 # the port that the container listens on
        imagePullPolicy: IfNotPresent

